name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build image and publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: kamko/lnu_ht19_ass
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          snapshot: true
